### ISSUE TITLE
添加自定义词典导致原先分对的词分错

### ISSUE THREAD

**Issue by tinyboy28** [lancopku/pkuseg-python#103]
@jingjingxupku 您好，最近在使用pkuseg分词工具，出现了这样的问题，想请教一下是什么原因：

如果不加用户词典，直接使用原始分词工具进行分词，是这样的结果：
import pkuseg
seg = pkuseg.pkuseg()
text = '我要看第16季'
seg.cut(text)
['我', '要', '看', '第16季']

如果我加了用户词典之后，进行分词，结果是这样的：
import pkuseg
seg = pkuseg.pkuseg(user_dict='dict.txt')
text = '我要看第16季'
seg.cut(text)
['我', '要', '看', '第1', '6', '季']

我检查了我的词典里面没有“第1”，“6”，“季”这样的内容，也没有在一些词里面包含“第1”这样的内容，为什么我没加词典能分好，加了以后反而分错了呢？是添加的词典产生的干扰吗？

_Originally posted by @tinyboy28 in https://github.com/lancopku/pkuseg-python/issues/59#issuecomment-548706272_

**Comment by yanchidezhang** [comment]
这个问题... 就么样被关闭了吗... 我看这好像是个比较普遍的问题呀
