### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/.pkuseg/postag/featureIndex.txt_0'

### ISSUE THREAD

**Issue by hjing100** [lancopku/pkuseg-python#144]
安装了pkuseg
初次使用，需要下载postag.zip
下载失败
我就自己下载，并放到文件夹下
但是有报错FileNotFoundError: [Errno 2] No such file or directory: '/home/.pkuseg/postag/featureIndex.txt_0'

**Comment by andrew-sn** [comment]
我下载了postag.zip，但是没有这个文件啊？featureIndex.txt_0

**Comment by Yuning-J** [comment]
Same problem occurs to me, even after downloading the postag.zip and put it under the correct place. Any suggestion please?

**Comment by dgzxx-2000** [comment]
下载了postag.zip，但是没有这个文件啊？featureIndex.txt_0
