### ISSUE TITLE
预训练模型能否存储到其他网盘

### ISSUE THREAD

**Issue by wangzhe258369** [lancopku/pkuseg-python#28]
预训练模型能否存储到其他网盘里，百度云的下载限速太厉害，很难用。谢谢！

**Comment by yaleimeng** [comment]
楼上你需要panDownloader。 @wangzhe258369

**Comment by wangzhe258369** [comment]
用那些网盘下载工具很容易被百度网盘封号的，那样百度网盘就彻底不能用了 @yaleimeng

**Comment by wangzhe258369** [comment]
Nice 谢谢！
