### ISSUE TITLE
分词结果并不理想怎么办呢？

### ISSUE THREAD

**Issue by zengchengli** [lancopku/pkuseg-python#33]
jieba&pkuseg分词效果对比
jieba分词：这个 不是 我刷 的 哦  
今天 可能 不行 啊 今天 工资 没到 账 今天 是 礼拜五 
你好 不是 对不起
           
pkuseg分词：这 个 不 是 我 刷 的 哦
今天 可能 不 行 啊 今天 工资 没 到 账 今天 是 礼拜五
你 好 不 是 对 不 起

我们可以看到在这个case下，pkuseg分词效果并不如jieba分词，我想问的是，如果想让pkuseg分词case下的分词效果比jieba分词效果好，应该如何去做呢？是测试所有的模型分词结果吗？还是说需要重新训练模型呢？

**Comment by dpuser6** [comment]
估计还是要自己在细分领域搞训练语料

**Comment by jingjingxupku** [comment]
感谢您的反馈，我们推出了新的工具包，新的工具包在分词效果和分词速度上均有提升，以下是新的工具包的输出结果：
```
In [1]: import pkuseg

In [2]: s = pkuseg.pkuseg()

In [3]: s.cut('这个不是我刷的哦')
Out[3]: ['这个', '不是', '我', '刷的', '哦']

In [4]: s.cut('今天可能不行啊今天工资没到账今天是礼拜五')
Out[4]: ['今天', '可能', '不行', '啊', '今天', '工资', '没', '到账', '今天', '是', '礼拜五']

In [5]: s.cut('你好不是对不起')
Out[5]: ['你好', '不是', '对不起']
```
