### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by xhochipe** [lancopku/pkuseg-python#38]
利用pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U pkuseg安装

import pkuseg

seg = pkuseg.pkuseg()

text = "我爱北京天安门"

cut = seg.cut(text)
print(cut)

Traceback (most recent call last):
  File "E:/python/work/spider/bx/piggy.py", line 1, in <module>
    import pkuseg
  File "D:\Program Files (x86)\Python\Anaconda3\lib\site-packages\pkuseg\__init__.py", line 14, in <module>
    import pkuseg.trainer
  File "D:\Program Files (x86)\Python\Anaconda3\lib\site-packages\pkuseg\trainer.py", line 19, in <module>
    import pkuseg.inference as _inf
  File "__init__.pxd", line 918, in init pkuseg.inference
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by Xfavor** [comment]
> 利用pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U pkuseg安装
> 
> import pkuseg
> 
> seg = pkuseg.pkuseg()
> 
> text = "我爱北京天安门"
> 
> cut = seg.cut(text)
> print(cut)
> 
> Traceback (most recent call last):
> File "E:/python/work/spider/bx/piggy.py", line 1, in 
> import pkuseg
> File "D:\Program Files (x86)\Python\Anaconda3\lib\site-packages\pkuseg__init__.py", line 14, in 
> import pkuseg.trainer
> File "D:\Program Files (x86)\Python\Anaconda3\lib\site-packages\pkuseg\trainer.py", line 19, in 
> import pkuseg.inference as _inf
> File "**init**.pxd", line 918, in init pkuseg.inference
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

numpy版本与pkuseg不兼容，建议升级numpy版本到最新

**Comment by jingjingxupku** [comment]
这个问题是由于numpy版本冲突导致的，为了避免这个问题，我们在最新版本里增加了版本限制，您可以重新安装使用。

**Comment by homesickjava** [comment]
我的pkuseg版本是0.0.22，numpy版本是 1.17.1，还是报这个异常，请问下这个这两个包需要下哪个版本的？

**Comment by JiaxiangBU** [comment]
这个问题解决后发现出现了问题 https://github.com/lancopku/pkuseg-python/issues/44
两者之间是循环。
