### ISSUE TITLE
python3.6 import 失败

### ISSUE THREAD

**Issue by tangchun** [lancopku/pkuseg-python#52]
>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuse
g
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pkuseg in d:\dev_tools\python3.6\lib\site-package
s (0.0.14)
Requirement already satisfied: numpy in d:\dev_tools\python3.6\lib\site-packages
 (from pkuseg) (1.13.3+mkl)

>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkuseg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\dev_tools\python3.6\lib\site-packages\pkuseg\__init__.py", line 14, i
n <module>
    import pkuseg.trainer as trainer
  File "D:\dev_tools\python3.6\lib\site-packages\pkuseg\trainer.py", line 19, in
 <module>
    import pkuseg.inference as _inf
  File "__init__.pxd", line 918, in init pkuseg.inference
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expec
ted 216 from C header, got 192 from PyObject

**Comment by chizengkun** [comment]
me too
use pip install pkuseg ，import error

env:
python 3.6.5
numpy 1.14.3

**Comment by longborn** [comment]
upgrade numpy 1.16.0

**Comment by jingjingxupku** [comment]
这个问题是由于numpy版本冲突导致的，为了避免这个问题，我们在最新版本里增加了版本限制，您可以重新安装使用。

**Comment by python-enthusiast** [comment]
解决方案是什么

**Comment by jingjingxupku** [comment]
> 解决方案是什么

您可以尝试如下几种方案：

1. pip安装最新版本的pkuseg代码，我们在最新版本的安装代码里加了版本限制，可以自适应numpy版本。
2. 如果以上不能解决您的问题，您可以尝试手动将numpy升级到numpy 1.16.0。
