### ISSUE TITLE
pip安装 使用细分领域模型 报错？

### ISSUE THREAD

**Issue by kinghmy** [lancopku/pkuseg-python#61]
`Traceback (most recent call last):
  9   File "py3_cook_corpus_embedding.py", line 18, in <module>
 10     seg = pkuseg.pkuseg(model_name='medicine') 
 11   File "/home/work/software/anaconda3/envs/py3myhao/lib/python3.6/site-packages/pkuseg/__init__.py", line 224, in __init__
 12     self.feature_extractor = FeatureExtractor.load()
 13   File "pkuseg/feature_extractor.pyx", line 625, in pkuseg.feature_extractor.FeatureExtractor.load
 14 FileNotFoundError: [Errno 2] No such file or directory: 'medicine/unigram_word.txt'`

另外，使用细分模型后，可以同时加上自定义词表吗？

**Comment by luoruixuan** [comment]
您好，请问您是否将pkuseg更新到了最新版本（0.0.18），以及运行过程中是否出现了下载的进度条？使用细分模型后可以同时加上自定义词典。

**Comment by Frank17** [comment]
遇到相同的问题，使用默认模型时，出现`No such file or directory: 'default/unigram_word.txt'`的错误，库是由github下载，并`python setup.py`的方式安装的
env
python3.5
centos6.8

**Comment by jingjingxupku** [comment]
由于模型参数问题，github的代码只上传了代码，如果您是从github上下载的话，预训练的模型需要您去release部分下载。以下是github下载并使用的基本流程：
1. 下载github代码
2. 下载预训练模型，并放到pkuseg文件夹下
3. 运行setup.py
4. 调用接口进行分词

如果您只是进行使用的话，推荐您使用更方便的pip安装方式。

**Comment by 46319943** [comment]
It may indicate your model path is not correctly set. You can refer to this solution:
https://github.com/explosion/spaCy/discussions/7370#discussioncomment-6415339

**Comment by kinghmy** [comment]
你好，来信我已收到，我会尽快处理，谢谢！
