### ISSUE TITLE
不能返回词性吗

### ISSUE THREAD

**Issue by lijc210** [lancopku/pkuseg-python#8]

**Comment by daiw10** [comment]
+1 同问这个问题，能够分词的同时返回词性么

**Comment by yanqiangmiffy** [comment]
对，看训练集就可以了，没有词性，只可以分词

**Comment by ArthurRizar** [comment]
+1，希望下一版本能加入词性，例如北大的词性表

**Comment by jingjingxupku** [comment]
我们此工具包的目的是想提供一个**细领域**的中文分词工具包， 目前还没有增加词性标注功能，不过下一步我们可能会考虑增加细领域的词性分析，谢谢您的问题。
