### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by LCorleone** [lancopku/pkuseg-python#81]
ImportError: /root/anaconda3/envs/NLP/lib/python3.5/site-packages/pkuseg/feature_extractor.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

ubuntu, pip install pkuseg
any ideas?

**Comment by LCorleone** [comment]
#73 
#51 
These two is similar

**Comment by LCorleone** [comment]
solved，strange problem.

**Comment by qq184861643** [comment]
@LCorleone Hi,could you plz tell me how did you solve this import error of pkuseg?

**Comment by LCorleone** [comment]
@qq184861643  reinstall

**Comment by yuboona** [comment]
@qq184861643 My experience using pkuseg with python3.5 asserted this error too, and reinstalling didn't work. Then I swiched to python3.6 and install, everything goes well now.
