### ISSUE TITLE
与其余分词工具包的性能对比并不公平吧？

### ISSUE THREAD

**Issue by jiesutd** [lancopku/pkuseg-python#9]
请问一下对比的jieba 和 THULAC 模型有用对应的训练语料（MSRA，CTB8）训练么？ 如果有训练语料的话，这两个模型的结果应该不会那么差。80%左右的F值都快和unsupervised segmentation 差不多了。

如果用in domain 训练语料训练的pkuseg  和  没有使用对应domain训练语料的jieba THULAC 对比，这样是显然不公平的啊。`大幅提高了分词的准确率`的结论不能通过这种对比实验得出。

事实上MSRA 分词效果在论文里基本上都超过97.5了。

**Comment by HaishuoFang** [comment]
赞同，我也有这个疑问，如果是用同一语料训练再用同一语料去测，这样的对比意义不是很大

**Comment by PatrickPro2** [comment]
同意，应该用这3个模型都没被训练过的数据集做仿真。用训练模型都数据集做评估，这本身就没有比较意义

**Comment by LittleNewton** [comment]
同意。感觉这个包有蹭北大光环的嫌疑。**we need 客观比较**。

**Comment by NickYi1990** [comment]
这种类型的对比都存在，很怀疑论文也是水的一笔~

**Comment by xxllp** [comment]
果然水

**Comment by yufengzhixing** [comment]
感觉评测不够严禁啊

**Comment by xxllp** [comment]
>           感觉评测不够严禁啊
严谨

**Comment by zhengwsh** [comment]
这是在测试集上做训练,效果肯定不会差啊....

**Comment by bamtercelboo** [comment]
分词测试出来的结果真是不符合人的直观思维，词语按照单字分开。

**Comment by ruanchong** [comment]
@yanqiangmiffy 不会吧，可能是一开始加载模型慢？多尝试几句话反而平摊起来更快

**Comment by Muzixin** [comment]
> 分词测试出来的结果真是不符合人的直观思维，词语按照单字分开。

嗨，能分享一下你的测试用例吗？

**Comment by xidiandb** [comment]
> 主要是效率太慢了，示例代码4 一句话分词用了2分钟。。

你是不是算了载入模型的时间

**Comment by x-hacker** [comment]
看完你们的评论。让我尝鲜的欲望都快没了....

**Comment by Cartus** [comment]
惊现二师兄

**Comment by alphadl** [comment]
看到公众号里面鼓吹的就知道是什么套路了，拿闭环数据去训练，在指定数据集打分，居然拿去和别的人人都在用的工业级分词对比。不知道是小编做公关还是作者本人写的，有点无知。像极了做机器翻译的拿比赛数据翻译结果去和谷歌翻译对比，然后说自己吊打谷歌翻译一般愚昧。

**Comment by aboutyang** [comment]
训练数据用来测试，这就是作弊

**Comment by jingjingxupku** [comment]
考虑到不同领域的数据对分词的效果影响很大，所以我们发布此工具包的初衷是想提供一个细领域的分词工具，让大家可以在使用的时候不用再受限于单一训练模型，而是可以根据领域特点自由地选择模型。目前我们提供了新闻领域、weibo领域以及混合领域的预训练模型。在比较的过程中，考虑到其他的分词工具包并没有提供细领域的预训练模型，所以我们在最初比较的时候仅使用了他们提供的通用训练模型。这个比较主要是为了反映使用细领域模型分词和使用通用领域模型分词的效果差别。考虑到比较的严谨性，除了对比细粒度领域模型分词和通用模型分词的效果差别，我们重新upload了其他方法在细领域上数据上训练和预测的结果，结果可见最新上传的readme。

**Comment by x-hacker** [comment]
> 考虑到不同领域的数据对分词的效果影响很大，所以我们发布此工具包的初衷是想提供一个细领域的分词工具，让大家可以在使用的时候不用再受限于单一训练模型，而是可以根据领域特点自由地选择模型。目前我们提供了新闻领域、weibo领域以及混合领域的预训练模型。在比较的过程中，考虑到其他的分词工具包并没有提供细领域的预训练模型，所以我们在最初比较的时候仅使用了他们提供的通用训练模型。这个比较主要是为了反映使用细领域模型分词和使用通用领域模型分词的效果差别。考虑到比较的严谨性，除了对比细粒度领域模型分词和通用模型分词的效果差别，我们重新upload了其他方法在细领域上数据上训练和预测的结果，结果可见最新上传的readme。

麻烦能不能支持一下Python2.7.....毕竟很多人都是用2.7开发

**Comment by jingjingxupku** [comment]
真的很委屈，我们也不知道为什么您会得出这样的结论。在readme的表格中，我们使用了msr的training data，在test data上进行测试。我们并没有使用training data训练，training data 测试。

**Comment by ypengc7512** [comment]
> 训练数据用来测试，这就是作弊
越传越离谱，人家训练的时候是拿训练数据训得吧，并没有用测试数据

**Comment by jingjingxupku** [comment]
@jiesutd 谢谢您的建议，我们增加了其他工具包在不同数据集上训练和测试的结果。测试结果可以参见readme。除此之外，为了便于大家复现我们的结果，我们还upload了在他们代码上预训练得到的模型。我们的工具包在msr的数据上也可以达到97+的效果，但是是由于引入了大量的feature，大大造成了模型运行的时间，所以我们为了实用性，折中的去掉了一些特别费时间的特征。不过为了避免误解，我们愿意将我们97+的模型也release出来。

我们此工具包的初衷只是想给大家提供更多细领域分词模型，这样大家可以不用再受限于单一领域语料的训练模型，而是可以根据自己的领域特点来自由地选择不同的预训练模型的工具。也许由于刚开源，现在的工具包还不完美，但我们愿意接受各位老师同学善意的建议继续完善我们的代码，再次感谢您善意的建议！

**Comment by jingjingxupku** [comment]
> 感觉评测不够严禁啊

@xxllp 针对您的意见，我们在最新的readme文件里公布了我们详细的评测方法。为了严谨性，我们将其他工具包在细领域的数据上也重新进行了训练和测试。不过需要强调的是我们此工具包并不是为了一种通用的分词模型，而是为不同领域的数据提供不同的预训练模型，这样大家可以根据自己待分词的领域特点，选择适合自己领域特点的模型进行分词。

**Comment by JustinLin610** [comment]
> 这是在测试集上做训练,效果肯定不会差啊....

msra和ctb8这些数据集都有切分训练集和测试集的

**Comment by jiesutd** [comment]
> @jiesutd 谢谢您的建议，我们增加了其他工具包在不同数据集上训练和测试的结果。测试结果可以参见readme。除此之外，为了便于大家复现我们的结果，我们还upload了在他们代码上预训练得到的模型。我们的工具包在msr的数据上也可以达到97+的效果，但是是由于引入了大量的feature，大大延长了模型运行的时间，所以我们为了实用性，折中的去掉了一些特别费时间的特征。不过为了避免误解，我们愿意将我们97+的模型也release出来。
> 
> 我们此工具包的初衷只是想给大家提供更多细领域分词模型，这样大家可以不用再受限于单一领域语料的训练模型，而是可以根据自己的领域特点来自由地选择不同的预训练模型的工具。由于刚开源，现在的工具包也许还不完美，但我们愿意接受各位老师同学善意的建议继续完善我们的代码，再次感谢您善意的建议！

你好，感谢回复，我现在明白了。
提供细分领域的分词模型很有用。现在加入细分领域的对比更清楚了。
只是最开始的网络宣传和文档中的对比方式确实有一定的误导，让人以为是通用的工具之间的对比。
不过我还是认为把细分领域的分词模型和通用的分词模型直接放一起对比不合适，因为完全不是一个赛道上的，没有可比性。我估计就算一个最简单的feed forward 模型在有训练集的情况下在对应领域也能大幅超越jieba THULAC。因此`大幅提高了分词的准确率` 这种宣传感觉有点overclaim。
这个issue 大家讨论的比较热烈，我就先不close了。

**Comment by jklj077** [comment]
> 都没被训练过的数据集做仿真。用训练模型的数据集做评估，这本身就没

**Comment by jingjingxupku** [comment]
> 同意，应该用这3个模型都没被训练过的数据集做仿真。用训练模型的数据集做评估，这本身就没有比较意义

为了解答您的疑惑，我们做了如下实验：

ctb训练 | msr | ctb | pku | weibo | all avg | ood avg
-- | -- | -- | -- | -- | -- | --
jieba | 82.75 | 87.14 | 87.12 | 85.68 | 85.67 | 85.18
thulac | 83.5 | 94.56 | 89.13 | 91.00 | 89.55 | 87.88
pkuseg | 83.67 | 95.69 | 89.67 | 91.19 | 90.06 | 88.18

all avg是所有测试集的平均，一定程度上反映平均性能
ood avg是除ctb测试集外其它测试集的平均，反映领域外分词性能

**Comment by jingjingxupku** [comment]
> 看到公众号里面鼓吹的就知道是什么套路了，拿闭环数据去训练，在指定数据集打分，居然拿去和别的人人都在用的工业级分词对比。不知道是小编做公关还是作者本人写的，有点不恰当。像极了做机器翻译的拿比赛数据翻译结果去和谷歌翻译对比，然后说自己吊打谷歌翻译一般。

您好，我们的初衷只是想提供一个细领域分词的工具包，我们在新闻语料和weibo语料均训练了不同的模型。而传统的模型只提供了通用的预训练模型接口，我们在最初比较的时候是想体现一下细领域分词和通用领域分词之间的差别，所以在我们的细领域模型和他们的通用模型上进行了比较。也许这种做法并不是很周到，所以我们增加了新的比较，为了严谨性，我们在同样的细领域的训练集上对他们的模型重新训练，在同样的细领域的测试集上重新测试。新的实验结果可参考最新的readme。@alphadl

**Comment by jingjingxupku** [comment]
> 训练数据用来测试，这就是作弊

@aboutyang 真的很委屈，我们也不知道为什么您会得出这样的结论。在readme的表格中，我们使用了msr的training data，在test data上进行测试。我们并没有使用training data训练和training data 测试。

**Comment by jingjingxupku** [comment]
> > 考虑到不同领域的数据对分词的效果影响很大，所以我们发布此工具包的初衷是想提供一个细领域的分词工具，让大家可以在使用的时候不用再受限于单一训练模型，而是可以根据领域特点自由地选择模型。目前我们提供了新闻领域、weibo领域以及混合领域的预训练模型。在比较的过程中，考虑到其他的分词工具包并没有提供细领域的预训练模型，所以我们在最初比较的时候仅使用了他们提供的通用训练模型。这个比较主要是为了反映使用细领域模型分词和使用通用领域模型分词的效果差别。考虑到比较的严谨性，除了对比细粒度领域模型分词和通用模型分词的效果差别，我们重新upload了其他方法在细领域上数据上训练和预测的结果，结果可见最新上传的readme。
> 
> 麻烦能不能支持一下Python2.7.....毕竟很多人都是用2.7开发

嗯嗯，谢谢您的建议，我们会尽快开发一个python2.7的版本供大家使用！

**Comment by yanqiangmiffy** [comment]
> > 主要是效率太慢了，示例代码4 一句话分词用了2分钟。。
> 
> 你是不是算了载入模型的时间

应该不是，算我误解了，我刚开始只以为一句话用两分钟，后来我试了下一整篇文章，差不多128秒，时间不是线性增加的，增加了一点。在此误判，不好意思

**Comment by yanqiangmiffy** [comment]
> 主要是效率太慢了，示例代码4 一句话分词用了2分钟。。

应该不是，算我误解了，我刚开始只以为一句话用两分钟，后来我试了下一整篇文章，差不多128秒，时间不是线性增加的，增加了一点。在此误判，不好意思

**Comment by yanqiangmiffy** [comment]
> > 主要是效率太慢了，示例代码4 一句话分词用了2分钟。。
> 
> 你是不是算了载入模型的时间



> @yanqiangmiffy 不会吧，可能是一开始加载模型慢？多尝试几句话反而平摊起来更快

嗯嗯，已更正，多谢

**Comment by rolinston4** [comment]
> > > 考虑到不同领域的数据对分词的效果影响很大，所以我们发布此工具包的初衷是想提供一个细领域的分词工具，让大家可以在使用的时候不用再受限于单一训练模型，而是可以根据领域特点自由地选择模型。目前我们提供了新闻领域、weibo领域以及混合领域的预训练模型。在比较的过程中，考虑到其他的分词工具包并没有提供细领域的预训练模型，所以我们在最初比较的时候仅使用了他们提供的通用训练模型。这个比较主要是为了反映使用细领域模型分词和使用通用领域模型分词的效果差别。考虑到比较的严谨性，除了对比细粒度领域模型分词和通用模型分词的效果差别，我们重新upload了其他方法在细领域上数据上训练和预测的结果，结果可见最新上传的readme。
> > 
> > 
> > 麻烦能不能支持一下Python2.7.....毕竟很多人都是用2.7开发
> 
> 嗯嗯，谢谢您的建议，我们会尽快开发一个python2.7的版本供大家使用！

Python官方都要在2020年停止python2.7的支持了， 把更多精力放到核心功能的提升上吧

**Comment by secsilm** [comment]
> > > 考虑到不同领域的数据对分词的效果影响很大，所以我们发布此工具包的初衷是想提供一个细领域的分词工具，让大家可以在使用的时候不用再受限于单一训练模型，而是可以根据领域特点自由地选择模型。目前我们提供了新闻领域、weibo领域以及混合领域的预训练模型。在比较的过程中，考虑到其他的分词工具包并没有提供细领域的预训练模型，所以我们在最初比较的时候仅使用了他们提供的通用训练模型。这个比较主要是为了反映使用细领域模型分词和使用通用领域模型分词的效果差别。考虑到比较的严谨性，除了对比细粒度领域模型分词和通用模型分词的效果差别，我们重新upload了其他方法在细领域上数据上训练和预测的结果，结果可见最新上传的readme。
> > 
> > 
> > 麻烦能不能支持一下Python2.7.....毕竟很多人都是用2.7开发
> 
> 嗯嗯，谢谢您的建议，我们会尽快开发一个python2.7的版本供大家使用！

请不要支持 Python 2

**Comment by zlj824635819** [comment]
本来是要用jieba来做分词的，看到了这个支持微博字典就用这个了，准确率并没有想象中的高，可能还是自己训练的模型更好用把。
